### ISSUE TITLE
GtCSVReader problems with jgrapht ConnectivityInspector

### ISSUE THREAD

**Issue by florisheijmans** [scify/JedAIToolkit#44]
This issue arose when I attempted to reproduce the workflow in: org.scify.jedai.demoworkflows.CsvDblpAcm.java.

During the reading process of the ground truths in DBLP-ACM_perfectMapping.csv (specifically the GtCSVReader.getDuplicatePairs method), the detection of connected components by the jgrapht package seems to not work.

For some reason I obtain a single cluster of size 2225 and then 5375 more clusters of size 1, which is obviously incorrect since the csv contains about 2225 unique pairs (which should in turn produce 2225 clusters of size 2).

Have you seen this problem before? Maybe the jgrapht package expects a different format than it did previously?

**Comment by mthanos** [comment]
Hi,

The problem indeed occurs because of the jgrapht update. The ' " ' characters are by default trimmed by the updated ConnectivityInspector and thus the ids are not recognized as existing keys when processed by the gt reader. We will have a more detailed look on this.
To resolve this issue for now you can remove those characters from the DPLP input file, or of course use a generally modified format.

Best regards,
Manos

________________________________

**Comment by florisheijmans** [comment]
Thank you! That fixes the problem.
