### ISSUE TITLE
DBPedia link broken

### ISSUE THREAD

**Issue by Murray1991** [scify/JedAIToolkit#52]
The [link for DBPedia](https://drive.google.com/open?id=1rFAwrmlsfR86fVIkOaGXCSzbfZIZufY2) in data/README.md doesn't work.

**Comment by gpapadis** [comment]
Hi! All datasets are available here: https://data.mendeley.com/datasets/4whpm32y47/7
You can also follow the instructions on this paper: http://helios.mi.parisdescartes.fr/~themisp/publications/is21-jedaiRepro.pdf in order to reproduce all experiments in the latest publication about JedAI (http://cgi.di.uoa.gr/~koubarak/publications/2020/JedAI_3D_ER.pdf).
Kind regards,
George
