### ISSUE TITLE
Dirty ER examples input .csv

### ISSUE THREAD

**Issue by vromaniello** [scify/JedAIToolkit#60]
Hi, it is possible to have sample files in .csv format for
- entity profile D1
- ground truth 
because .csv files with any formatting will not work.
The error from JedAI-gui is the following:

![image](https://user-images.githubusercontent.com/87575909/174116861-6b372f05-f148-42d7-ad97-dc87e39b8b69.png)

Thanks you for the support

**Comment by gpapadis** [comment]
Hi Vito,

thanks for your interest in JedAI!

The error you get is caused by an incompatibility between JedAI-gui and JedAI-core. The former is practically deprecated. It's better to use JedAI's web app through Docker. See Table 4 here for instructions: https://helios2.mi.parisdescartes.fr/~themisp/publications/is21-jedaiRepro.pdf .

Still, our custom implementation of the CSV reader gets confused by the separator, when it's not a comma. The best approach is to format your dataset like the Leipzig benchmarks (https://dbs.uni-leipzig.de/research/projects/object_matching/benchmark_datasets_for_entity_resolution), using comma as a separator and quotes for the values. Below you can find screenshots showing that JedAI can successfully read the csv files of the Abt-Buy dataset.

Btw, some of the Leipzig datasets involve more than than one duplicate per entity, even though they are Clean-Clean ER datasets. This is not supported by JedAI, which automatically removes equivalence clusters with more than two entities and prints the relevant messages in the command line.

![Screenshot from 2022-06-20 19-05-24](https://user-images.githubusercontent.com/12528194/174643466-89564f2b-76e2-43ae-b54c-54f37994e4ea.png)

![Screenshot from 2022-06-20 19-05-34](https://user-images.githubusercontent.com/12528194/174643458-1fc46a6f-44c8-4c70-8d6f-9c51a821a884.png)

**Comment by vromaniello** [comment]
Thanks! My tests succedeed with JedAI's web app through Docker.
